package com.example.madhan.wicc;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ListView;
import android.widget.Toast;

public class TechnicalCommiteeActivity extends AppCompatActivity {

    private String[] name = {
            "Dr. Natarajan Meghanathan",
            "Prof Ir Dr VignaKumaranRamachandaramurthy",
            "Prof. Dr. Sanjay Misra",
            "Prof. Dipanwita Roy Chowdhury",
            "Dr. AtulGarg",
            "Dr. Sudhanshu Kumar Jha",
            "Dr. Dilip Singh Sisodia",
            "Dr. Sanjeev Kumar",
            "Dr. P. S. Avadhani",
            "Dr. Anil Kumar Dubey",
            "Shri Rakesh Kumar Sehgal",
            "Dr. Sanjay Sood",
            "Prof. Ch A S Murty",
            "Dr.Neeta Singh",
            "Dr. S. Mini",
            "Dr. K ShashiPrabh",
            "Dr. Chittaranjan Pradhan",
            "Dr.D.Kavitha",
            "Dr. T S Chandar",
            "Dr KVSVN Raju",
            "Dr. Debashis De",
            "Dr. V. K. Jain",
            "Dr. Diwakar Bhardwaj",
            "Dr.Charu",
            "Dr.Sobhana N V",
            "Dr.S.G Balakrishnan",
            "Prof M.Shashi",
            "Dr. K Satyanarayan Reddy",
            "Dr.PraveenChakkravarthy",
            "Dr.R.Praveen Sam",
            "Dr. Rajesh R",
            "Dr.R. Vijayakumar",
            "Dr. ChitraBabu",
            "Dr. J. Immanuel Johnraja",
            "Dr. N. Prasath",
            "Prof. SmrithiRekha",
            "J.Nafeesa Begum",
            "Dr.K.Baskaran",
            "Dr. R Nedunchezhian",
            "Dr. A.Balamurugan,",
            "Dr. LathaParameswaran",
            "Dr.M.Sandhya",
            "Prof. M S Rohit",
            "Dr.AngelinaGeetha",
            "Dr. J. C. Miraclin Joyce Pamila",
            "Dr. A. JameerBasha",
            "Dr. Kannan Balasubramanian",
            "Dr. K. AnithaKumari",
            "Dr.S.S.Sridhar",
            "Dr.D.Surendran",
            "Dr.P.Golda Jeyasheeli",
            "Dr.T.Rajendran",
            "Dr. T. Kalaiselvi",
            "Dr.Anil Kumar Verma",
            "Prof. Christopher paul A",
            "Dr.S. Joseph Gladwin",
            "Dr. M. Usha, Professor",
            "Dr.Hamsapriya",
            "Dr. H. N. Suresh",
            "Prof. Dr. R. Elijah Blessing",
            "Dr. Julia Punitha Malar Dhas",
            "Dr.M.Akila",
            "Dr. B. Surendiran",
            "Dr.S.Malliga",
            "Dr.M.Chinnadurai",
            "Dr.Gopalakrishnan.K",
            "Dr.Jayashree L.S.",
            "Dr.Thangarajan R",
            "Dr.Lill Beaulah H",
            "Dr.Minu R.I.",
            "Dr. S. Shankar",
            "Dr.J.Jesu Vedha Nayahi",
            "Dr.A.Bazila Banu",
            "Dr.Jeevaa Katiravan",
            "Dr.R.C.Suganthe",
            "Dr.T.Senthil Kumar",
            "Dr. K. Premalatha",
            "Dr.N.Shanthi",
            "Dr, R. Kanchana",
            "Dr.R.Jemila Rose",
            "Dr. G. Raghu Raman",
            "Dr.Avanija J",
            "Dr.Paul Rodrigues",
            "Dr.R.R. Rajalaxmi",
            "Dr.B. Bharathi",
            "Dr. K. Dhanalakshmi",
            "Dr. D. Chitra",
            "Dr. P. Latha",
            "Dr.N.Karthikeyan",
            "Dr.M.Marikkannan",
            "Dr.D. Sasikala",
            "Dr.S.Jabeen Begum",
            "Dr. A. M. Kalpana",
            "Dr.S.Ayyasamy",
            "Dr.B.Rajalakshmi",
            "Dr. Godfrey winstersathianesan",
            "Dr. A. Grace Selvarani",
            "Dr.A.R.Kavitha, Professor",
            "Dr. B.Raveendra Babu",
            "Dr. L.Latha",
            "Dr.Kuppusamy P",
            "Dr.P.Natesan",
            "Ms.S.Rajini",
            "Dr. G.Manikandan",
            "Dr. B.Latha",
            "Dr. MarimuthuKaruppiah",
            "Dr..S.Kannan, Professor",
            "Dr.G.S.Nandakumar",
            "Dr. Askarunisa A",
            "Dr. S.Padmavathi,",
            "Dr.S.Jenicka",
            "Dr.K.Jayashree",
            "Dr Rashid Ali",
            "Dr.P.Varalakshmi",
            "Dr.Shreelekshmi R",
            "Dr.M.Aramudhan",
            "Dr. S. Kannimuthu",
            "Dr. K.Ramesh Babu",
            "Dr M Sadish Sendil",
            "Dr. V. Chandrasekar",
            "Mr. B.Sudhakar",
            "Dr.J.sangeetha",
            "Dr.R.Muthuselvi",
            "Dr. G. Nagappan",
            "Dr.P.Madhavan"
    };

    private String[] desc = {
            "Professor, Jackson State University, USA",
            "Institute of Power Engineering, UniversitiTenagaNasional, MALAYSIA",
            "Professor, Chair of Center of ICT/ICE-Software and Hardware, Covenant University, NIGERIA",
            "Chairman, Kalpana Chawla Space Technology Cell, IIT Kharagpur, INDIA",
            "Associate Professor,M. M. Institute of Computer Technology & Business Management, Mullana (Ambala), INDIA",
            "Assistant Professor, National Institute of Technology Jamshedpur, INDIA",
            "Assistant Professor & Head, National Institute of Technology Raipur, INDIA",
            "Professor & Head, Agra University, INDIA",
            "Principal, College of Engineering Andhra University, Visakhapatnam, INDIA",
            "Associate Professor, Poornima Institute of Engineering & Technology, Jaipur, INDIA",
            "Joint Director & Head of Department, CDAC, INDIA",
            "Jt. Director (Healthcare Informatics) C-DAC Mohali, INDIA",
            "Joint Director C-DAC, INDIA",
            "Assistant Professor, Gautam Buddha University, Uttar Pradesh, INDIA",
            "Assistant Professor, National Institute of Technology Goa, INDIA",
            "Shiv Nadar University, Uttar Pradesh, INDIA",
            "Assistant Professor, KIIT University, Bhubaneswar, INDIA",
            "Professor, G.Pulla Reddy Engineering College, Kurnool, INDIA",
            "Professor, PES University, Karnataka, INDIA",
            "Professor, Anil Neerukonda Institute of Technology & Sciences, Visakhapatnam, INDIA",
            "Professor, MaulanaAbulKalam Azad University of Technology, West Bengal, INDIA",
            "Dean, Mody University of Science and Technology, Rajasthan, INDIA",
            "Principal, University of Polytechnic, GLA University, U.P., INDIA",
            "Associate Professor, Jaypee Institute of Information Technology, Uttar Pradesh, INDIA.",
            "Professor, Rajiv Gandhi Institute of Technology, Kerala, INDIA",
            "Professor, APS College of engineering, Karnataka, INDIA",
            "Professor, Andhra University -College of Engineering, Visakhapatnam, INDIA",
            ", Professor & Head, Cambridge Institute of Technology, Karnataka, INDIA",
            "CVR College of Engineering, Hyderabad, INDIA",
            "Professor, G. Pulla Reddy Engineering College (Autonomous), Andhra Pradesh, INDIA",
            "Central University of Kerala, INDIA",
            "Professor, Mahatma Gandhi University, Kerala, INDIA",
            "Professor & Head, SSN College of Engineering, Tamil Nadu, INDIA",
            "Professor & Head, Karunya University, Tamil Nadu, INDIA",
            "Associate Professor, KPR Institute of Engineering and Technology, Tamil Nadu, INDIA",
            "Amrita University, Tamil Nadu, INDIADr.",
            "Government College of Engineering-Bargur, Tamil Nadu, INDIA",
            "Government College of Technology-Coimbatore, Tamil Nadu, INDIA",
            "Professor, Coimbatore Institute of Technology, Tamil Nadu, INDIA",
            "Sri Krishna College of Technology, Tamil Nadu, INDIA",
            "Professor & Chairperson, Amrita VishwaVidyapeetham, Tamil Nadu, INDIA",
            "Professor & Head, B.S.Abdur Rahman University, Tamil Nadu, INDIA",
            "Assistant Professor, Jain Institute of Technology, INDIA",
            "Professor, BSA CRESCENT UNIVERSITY, Tamil Nadu, INDIA",
            "Assistant Professor (Senior Grade), Government College of Technology, Tamil Nadu, INDIA",
            "Professor & Head, Sri Krishna College of Technology, Tamil Nadu, INDIA",
            "Professor, MepcoSchlenk Engineering College, Tamil Nadu, INDIA",
            "PSG College of Technology, Tamil Nadu, INDIA",
            "SRM University, Tamil Nadu, INDIA",
            "Professor, SKCET, Tamil Nadu, INDIA",
            "Professor, MepcoSchlenk Engineering College, Tamil Nadu, INDIA",
            "Periyar University, Tamil Nadu, INDIA",
            "The Gandhigram Rural Institute - Deemed University, Tamil Nadu, INDIA",
            "Professor, Thapar University, Punjab, INDIA",
            "Assistant Professor, SNSCT, Tamil Nadu, INDIA",
            "Associate Professor, SSN College of Engineering, Tamil Nadu, INDIA",
            "Sona college of technology, Tamil Nadu, INDIA",
            "Professor & Head, PSG Institute of Technology & Applied Research, Tamil Nadu, INDIA",
            "Professor, Malnad College of Engineering, Karnataka, INDIA",
            "Registrar, Karunya University, Tamil Nadu, INDIA",
            "Professor & Head, Noorul Islam University, Tamil Nadu, INDIA",
            "Professor, KPR Institute of Engineering and Technology, Tamil Nadu, INDIA",
            "Assistant professor & HOD, National Institute of Technology Puducherry",
            "Professor, Kongu Engineering College, Tamil Nadu, INDIA",
            "Professor & Head, EGS Pillay Engineering College, Tamil Nadu, INDIA",
            "Loyola-Icam College of Engineering and Technology, Tamil Nadu, INDIA",
            "PSG College of Technology, Tamil Nadu, INDIA",
            "Professor, Kongu Engineering College, Tamil Nadu, INDIA",
            "Professor, Mahendra College of Engineering, Tamil Nadu, INDIA",
            "Professor, Jerusalem College of Engineering, Tamil Nadu, INDIA",
            "Professor, Sri Krishna College of Engineering and Technology, Tamil Nadu, INDIA",
            "Assistant Professor, Anna University Regional Campus Tirunelveli, Tamil Nadu, INDIA",
            "Assistant Professor, Bannari Amman Institute of Technology, Tamil Nadu, INDIA",
            "Associate Professor and Head, Velammal Engineering college, Tamil Nadu, INDIA",
            "Professor, Kongu Engineering College, Tamil Nadu, INDIA",
            "Associate Professor, Amrita School of Engineering, Tamil Nadu, INDIA",
            "Professor, Bannari Amman Institute of Technology, Tamil Nadu, INDIA",
            "Professor, Kongu Engineering College, Tamil Nadu, INDIA",
            "Associate Professor, SSN College of Engineering, Chennai, Tamil Nadu, INDIA",
            "Associate Professor, St.Xavier's Catholic College of Engg, Chunkankadai, Nagarkoil, Tamilnadu, INDIA.",
            "Associate Professor, SSN College of Engineering, Chennai, Tamil Nadu, INDIA",
            "Professor, RVS Educational Trusts Group of Institution, Dindigul, Tamil Nadu, INDIA",
            "Professor, DMI College of Engg., Chennai, Tamil Nadu, INDIA",
            "Professor, Kongu Engineering College, Erode, Tamil Nadu, INDIA",
            "Associate Professor, SSN College of Engineering, Chennai, Tamil Nadu, INDIA",
            "Professor, PSNACET, Dindigul, Tamil Nadu, INDIA",
            "Professor, P. A. College of Engineering and Technology,Pollachi, Coimbatore, Tamil Nadu, INDIA",
            "Professor, Government College of Engineering Tirunelveli,Tamil Nadu, INDIA.",
            "Professor, Syed Ammal Engineering College, Ramanathapuram, Tamil Nadu, INDIA.",
            "Professor, IRTT, Erode, Tamilnadu, India",
            "Professor, Bannari Amman Insitute of Technology, Sathyamangalam, Tamilnadu, India",
            "Professor, Velalar College of Engineering and Technology,Erode, Tamilnadu, India",
            "Professor, Government College of Engineering Tirunelveli,Tamil Nadu, INDIA",
            "Professor, Dr.NGP Institute of Technology,Coimbatore, Tamil Nadu, INDIA",
            "Professor, Velammal Engineering College, Chennai, Tamil Nadu, INDIA",
            "Professor, Saveetha Engineering College, Chennai, Tamil Nadu, INDIA",
            "Professor, Sri Ramakrishna Engineering College, Coimbatore, Tamil Nadu, INDIA",
            "Jerusalem college of Engineering, Chennai, Tamil Nadu, INDIA",
            "Professor, RVR & JC College of Engineering, Guntur, Tamil Nadu, INDIA",
            "Associate Professor, Kumaraguru College of Technology,Coimbatore, Tamil Nadu, INDIA",
            "Professor, Gnanamani College of Technology, Pachal, Namakkal, Tamil Nadu, INDIA",
            "Professor, Kongu Engineering College,Perundurai,Erode, Tamil Nadu, INDIA",
            "Associate Professor, Kumaraguru College of Technology,Coimbatore, Tamil Nadu, INDIA",
            "Professor, Tirumala Engineering College, Hyderabad, Telungana, Andhra Pradesh, INDIA.",
            "Professor, Sri Sairam Engineering College,Chennai, Tamil Nadu, INDIA",
            "Associate Professor, VIT University,Vellore, Tamil Nadu, INDIA",
            "E.G.S.Pillay Engineering College,Nagapattinam, Tamil Nadu, INDIA",
            "Associate Professor, Kumaraguru College of Technology,Coimbatore, Tamil Nadu, INDIA.",
            "Professor,KLN College of Engineering and Technology, Madurai, Tamilnadu, INDIA.",
            "Associate Professor, Thiagarajar College of Engineering, Madurai, Tamil Nadu, INDIA",
            "Associate Professor, Sethu Institute of Technology, Kariapatti, Tamil Nadu, INDIA",
            "Assistant Professor, anara Engineering College, Benjanapadavu, Karnataka, INDIA.",
            "Associate Professor, Department of Computer Science and Engineering, Aligarh Muslim University, Aligarh, Uttar Pradesh, INDIA.",
            "Assistant Professor [Sr.Gr], Department of Information Technology, Anna University, Chennai, Tamil Nadu, INDIA.",
            "Professor, Department of Computer Science and Engineering, College of Engineering Trivandrum, Kerala.",
            "Associate Professor, Department of Information Technology, Perunthalaivar Kamarajar Institute of Engineering and Technology, Nedungadu Karikal, Pondicherry.",
            "Associate Professor, Department of CSE, Karpagam College of Engineering, Coimbatore, Tamil Nadu, INDIA.",
            "Associate Professor, VIT UNIVERSITY, Vellore, Tamil Nadu, INDIA.",
            "Assistant Professor Faculty of Information Systems & Technology SUR University College Sultanate of Oman, OMAN.",
            "Professor, Department of CSE, Vimal Jyothi Engineering College, Kerala, INDIA.",
            "Assistant Professor, Department of ECE, Annamalai University, Chidambaram, Tamil Nadu, INDIA.",
            "Assistant Professor, Department of IT, SASTRA University, Tanjore, Tamil Nadu, INDIA.",
            "Professor, Department of CSE, Kamaraj College of Engineering and Technology, Virudhunagar, Tamil Nadu, INDIA",
            "Professor, Department of CSE, Saveetha Engineering College, Chennai, Tamil Nadu, INDIA.",
            "Associate Professor, Department of CSE, Sri Krishna College of Technology, Coimbatore, Tamil Nadu, INDIA."
    };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_technical_commitee);

        ListView listView = (ListView) findViewById(R.id.technicalCommitee);


        ListLayoutWithoutImage adapter = new ListLayoutWithoutImage(this, name, desc);
        listView.setAdapter(adapter);

        listView.setOnItemClickListener(new AdapterView.OnItemClickListener() {

            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                String item= name[position];
                Toast toast = Toast.makeText(getApplicationContext(), item, Toast.LENGTH_SHORT);
                toast.show();
            }
        });
    }
}
